[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****
- Users can add locations in different categories like: shops, bars, restaurants, sights, monuments, etc.
- Users will be able to show the locations in a map window.
- Users can add review scores, comments, pictures, etc. about the added places.
- It will be possible to manage from the application the information that is accessible with other users, like their friends or groups of friends.
- The information about a place stored by each user should not be centralized and should be stored in each user’s pod.
- If it is considered necessary, the system could store other information in a centralized way for performance reasons trying to respect the privacy of the users as much as possible.
- The system will allow users to see places and information about those places taken from their friends.
- The system will allow users to see the map with filters like by category, friends, etc.



=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
- Aesthetics and usability by non technical people.
- Security and respect for user's privacy.
- Responsiveness of the application.
- Interoperability between the data stored by the different applications.
- Originality of the solution.
- Tests code coverage and quality of test strategy.

- Continuous integration (CI) and continuous delivery (CD) strategy.
- Quality of technical documentation taking into account architecture decision records.
- Code quality analyzed both manually and automatically.
- Project management aspects like proper use of issues, meeting notes, code reviews, architecture decision records, etc.
    

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Citizens >_ | _<?>_ | _<Be able to use an aplication where they can have custom maps about places and businesses>_
| _<Council of Brussels>_ | _<?>_ | _<Meet the needs of citizens, whatever those are>_
| _<HappySw Owner>_ | _<?>_ | _<Create a good application which could result in more jobs>_
| _<HappySw Arquitect>_ | _<?>_ | _<?>_
| _<HappySw Developers>_ | _<Miguel Suárez, Damián Fernández, Rubén Caño, David González>_ | _<Desarrollar la aplicacióin según la arquitectura diseñada>_
|===
