[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

=== Technological Decisions

For the development of the application we have decided to use the following technologies:

* SOLID: Solid is perfect for the development of this application, since it allows users to maintain their privacy by storing information in their personal pods.
* React.js: We chose react for its simplicity, ease of learning, and reliability (as it is a widely used library in the industry, it is highly error-tested).
* Node.js: Node allows you to manage multiple connections at the same time, thanks to the fact that it is an asynchronous runtime environment. Besides, it allows a very fast execution of JavaScript.
	


	
