[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== User Login and Logout

[plantuml,"Sequence diagram login",png]
----
actor User
Participant LoMap
participant ra as "RESTAPI"
database pod as "Pod's provider"
User --> LoMap : Start
LoMap  --> User : Shows login view
User --> LoMap : Select the provider and login
LoMap  --> ra: Calls login
ra --> pod: Login in provider
pod --> User: Ask for credentials
User --> pod: Give credentials
pod --> ra: Return and create session
ra --> LoMap: Redirect
LoMap --> User: Shows map view
User--> LoMap: Clicks logout
LoMap --> ra: Calls logout
ra --> ra: Delete sesion from storage
ra --> pod: Calls sesion logout
LoMap --> User: Shows login view
----

=== Return all location of the map
[plantuml,"Sequence diagram return all location",png]
----
actor User
Participant LoMap
participant ra as "RESTAPI"
database pod as "Pod's provider"
User --> LoMap: Login in the application
LoMap --> ra: Request the all the locations of the user
ra --> pod: Asks for all the locations stored in the users pod
pod --> ra: Return all the locations
ra --> LoMap: Gives all the locations
LoMap --> User: Shows all the locations in the map
----
A user logs into the application and the first thing the application do is load all the locations.

=== Add location to the map
[plantuml,"Sequence diagram add",png]
----
actor User
Participant LoMap
participant ra as "RESTAPI"
database pod as "Pod's provider"
User --> LoMap: Clicks the option to add a location and clicks the map
LoMap --> User: Shows the form to add the location
User --> LoMap: Returns location data
LoMap --> ra: Save the location
ra --> pod: Stores the location in the users pod
pod --> ra: Gives the locations with the one added
ra --> LoMap: Return all the locations
LoMap --> User: Shows all the locations of the user
----
A user adds a new point 

=== Delete location of the map
[plantuml,"Sequence diagram delete",png]
----
actor User
Participant LoMap
participant ra as "RESTAPI"
database pod as "Pod's provider"
User --> LoMap: Select the location that whant to be deleted
LoMap --> User: Shows the full information of the place with the option to delete
User --> LoMap: Select the delete option
LoMap --> ra: Remove the location
ra --> pod: Delete the location
pod --> ra: Gives the locations with the one deleted
ra --> LoMap: Return all the locations 
LoMap --> User: Shows all the locations of the user withot the one deleted

----
A user deletes an existing point 

=== Modify location of the map
[plantuml,"Sequence diagram modify",png]
----
actor User
Participant LoMap
participant ra as "RESTAPI"
database pod as "Pod's provider"
User --> LoMap: Select the location that whant to be modify
LoMap --> User: Shows the full information of the place with the option to modify
User --> LoMap: Select the modify option
LoMap --> User: Shows the filds that can be modify
User --> LoMap: Modifies tha fields
LoMap --> ra: Modifies the location fields
ra --> pod: Modifies the location
pod --> ra: Gives the locations with the one modified
ra --> LoMap: Return all the locations 
LoMap --> User: Shows all the locations of the user with the one modified
----
A user modifies an existing point 