[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****
[plantuml,"Infrastructure",png]
----
Actor User

node Device {
    component WebBrowser 
}

node Netlify{
    component WebApp
    component Controllers
}

node sl as "SOLID POD"
node GoogleMaps

User -r-> Device 
WebBrowser -r-> Netlify
WebApp -d-> GoogleMaps 
Controllers -d-> sl
----

Motivation::

During the development of the application it runs on each person’s machine. However, the final product, it's been executed on a server hosted with Netlify.

Quality and/or Performance Features::
Our application depends on many different APIs, some of them are to show the map and to manage the PODs. We cannot control these APIs, so the availability and efficiency of the application may be affected. Also, these quality features could be affected by the server.

Mapping of Building Blocks to Infrastructure::
[options="header"] 
|===
| Block Name | Description
| Netlify | Is in charge of the web access of the application
| GoogleMaps | API that provides us the map where the user is going to operate the application and manage all the data.
| SOLID POD | Personal and private data storage that each user has. All the private data that the user needs for the application or the data that the user generates it's going to be stored here. 
| Device | Device that the user is going to use. Should need internet connection. 
|===