[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****
[plantuml,"Infrastructure",png]
----
Actor User

node Device {
    node WebBrowser {
        component WebAppImage
    }
}

node Server{
    node DockerCompose{
        node DockerWeb{
            component WebApp
        } 
        node DockerAPI{
            component RESTAPI
        }
    }
}

node sl as "SOLID POD"
node GoogleMaps

User -r-> WebAppImage 
RESTAPI -d-> sl : User data management
WebAppImage -d-> GoogleMaps: Supply the main map
WebApp -d-> WebAppImage 
----

Motivation::

To test the app, it runs on each person's machine. However, when the development of the application progresses, it will be executed on a server that has a DockerCompose with the Dockers that contains the WebApp, which is where the user interacts, and another with the REST API, which is the part that manages the data. 

Quality and/or Performance Features::
Our application depends on many different APIs, some of them are to show the map and to manage the PODs. We cannot control these APIs, so the availability and efficiency of the application may be affected. Also, these quality features could be affected by the server where the Dockers are running.

Mapping of Building Blocks to Infrastructure::
[options="header"] 
|===
| Block Name | Description
| DockerWeb | Container that englobe all the WebApp part of the application, the user interface that the user interacts with.
| DockerAPI | Container that englobe all the REST API part of the application, the part that manages the data.
| DockerCompose | Container that englobe all the application for an easier deployment.
| Server | Server that is in charge of the web access of the application.
| GoogleMaps | API that provide us the map where the user is going to operate the application and manage all the data.
| SOLID POD | Personal and private data storage that each user has. All the private data that the user needs for the application or the data that the user generates its going to be stored here. 
| Device | Device that the user is going to use. Should need internet connection. 
|===