[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****
=== Risks

[options="header",cols="1,2"]
|===
|Risk|Brief description
| _Big Proyect_ | Being a large project compared to the projects we have done so far, communication and collaboration will be very important to have a good result in its development.
|===


=== Technical debts


[options="header",cols="1,2"]
|===
|Technical debts|Brief description
| _Lack of experience_ | None of the team members have any experience in the use of technologies such as: React, Node, Solid... , which means that we have to make an initial effort to learn these technologies.
|===