name: custom Continuous deployment for LOMAP ES1c

on: [release]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    # Clean and install
    - run: npm --prefix frontend ci                     
    
    # Run tests
    - run: npm --prefix frontend test --coverage --watchAll

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  

  docker-build-push:
    name: Build the Docker image and push it to Github Packages
    runs-on: ubuntu-latest

    # Wait for tests to finish
    needs: [unit-tests]

    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        GOOGLE_MAPS_AKI_KEY: ${{ secrets.GOOGLE_MAPS_AKI_KEY }}
      with:
        name: uo276818/lomap_es1c
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: frontend
        tags: "latest"
        # No registry because pushing to hub.docker.com
