name: custom CI for LOMAP ES1c

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    # Clean and install
    - run: npm --prefix frontend ci                     
    # - run: npm --prefix backend ci
    
    # Run tests
    - run: npm --prefix frontend test --coverage --watchAll
    # - run: npm --prefix backend test --coverage --watchAll

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  test_e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - run: npm --prefix frontend ci
    - run: npm --prefix frontend start &

    - uses: iFaxity/wait-on-action
      with:
        resource: http://localhost:3000

    - run: npm --prefix frontend run test:e2e
